services:
  # Backend (Spring Boot) - Conecta a AWS RDS PostgreSQL
  backend:
    image: ${DOCKER_USERNAME}/kuhub-app:backend-${TAG}
    container_name: kuhub-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${KU_AWS_AC_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${KU_AWS_AC_DB_PASS}
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx1024m -Xms768m
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_ORM_JDBC_BIND=TRACE
    deploy:
      resources:
        limits:
          memory: 1400M
        reservations:
          memory: 1024M

  # Frontend (React + Nginx)
  frontend:
    image: ${DOCKER_USERNAME}/kuhub-app:frontend-${TAG}
    container_name: kuhub-frontend
    restart: always
    ports:
      - "127.0.0.1:3000:80"
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M