package KuHub.modules.gestion_academica.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "asignatura")
@Getter@Setter@NoArgsConstructor@AllArgsConstructor@ToString
public class Asignatura {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_asignatura")
    private Integer idAsignatura;

    @Column(name = "cod_asignatura", length = 50, nullable = false, unique = true)
    private String codAsignatura;

    @Column(name = "nombre_asignatura", length = 100, nullable = false)
    private String nombreAsignatura;

    @Column(name = "activo")
    private Boolean activo ;

    @Column(name = "descripcion", length = 250 )
    private String descripcion;

    /** 24/11/25 fecha de modificacion de la bbdd
     * -- Tabla asignatura
     * CREATE TABLE asignatura (
     *     id_asignatura INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     *     cod_asignatura VARCHAR(50) UNIQUE NOT NULL,
     *     nombre_asignatura VARCHAR(100) NOT NULL,
     *     activo BOOLEAN DEFAULT TRUE,             -- soft delete
     * 	descripcion VARCHAR(250)              	 -- nueva columna
     * );
     * */
}
