package KuHub.modules.gestion_academica.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "sala")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Sala {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_sala")
    private Integer idSala;

    @Column(name = "cod_sala", unique = true, length = 50)
    private String codSala;

    @Column(name = "nombre_sala", length = 100)
    private String nombreSala;

    @Column(name = "activo")
    private Boolean activo = true;

    /** 24/11/25 fecha de modificacion de la bbdd
     *-- Tabla sala
     * CREATE TABLE sala (
     *     id_sala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     *     cod_sala VARCHAR(50) UNIQUE,
     *     nombre_sala VARCHAR(100),
     *     activo BOOLEAN DEFAULT TRUE
     * );
     * */
}
