package KuHub.modules.gestion_academica.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name ="seccion")
@Getter@Setter@NoArgsConstructor
@AllArgsConstructor@ToString
public class Seccion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_seccion")
    private Integer idSeccion;

    // Relación ManyToOne con Asignatura
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_asignatura", nullable = false)
    private Asignatura asignatura;

    @Column(name = "nombre_seccion", length = 100, nullable = false)
    private String nombreSeccion;

    @Column(name = "capacidad_max", nullable = false)
    private Short capacidadMax;

    @Column(name = "cant_inscritos", nullable = false)
    private Short cantInscritos;

    @Column(name = "activo", nullable = false)
    private Boolean activo = true;

    // NUEVO: estado de la sección
    @Enumerated(EnumType.STRING)
    @Column(name = "estado_seccion", nullable = false)
    private EstadoSeccion estadoSeccion = EstadoSeccion.ACTIVA; // valor por defecto

    /**
     * Permite vincular la asignatura usando solo el ID.
     * Evita tener que buscar la entidad completa en la DB antes de guardar.
     */
    public void setIdAsignatura(Integer id) {
        if (id != null) {
            this.asignatura = new Asignatura();
            this.asignatura.setIdAsignatura(id);
        }
    }

    public enum EstadoSeccion {
        ACTIVA,
        INACTIVA,
        SUSPENDIDA
    }

    /**Usada para controlar al momento de crear la seccion si el usuario es de rol DOCENTE O PROFESOR_A_CARGO
     * Esto permite ser escaleble al momento de agregar nuevos roles al crear seccion*/
    public enum RolValido {
        DOCENTE,
        PROFESOR_A_CARGO;
    }

    /** 10/03/26 actualizado
     * -- Tabla seccion
     * CREATE TABLE seccion (
     * 	id_seccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     * 	id_asignatura INTEGER NOT NULL,
     * 	nombre_seccion VARCHAR(100) NOT NULL,
     * 	capacidad_max SMALLINT NOT NULL,
     * 	cant_inscritos SMALLINT NOT NULL,
     * 	activo BOOLEAN DEFAULT TRUE, -- soft delete
     * 	estado_seccion estado_seccion_type NOT NULL DEFAULT 'ACTIVA',
     * 	CONSTRAINT fk_asignatura
     * 		FOREIGN KEY (id_asignatura)
     * 		REFERENCES asignatura(id_asignatura)
     * ); */
}
