# ===== DATASOURCE CONFIGURATION =====
# CONFIGURACIÓN (GIT + LOCAL)
# Usamos variables para que GitHub Actions inyecte los secretos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA/HIBERNATE CONFIGURATION =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar consultas SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Inicialización
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

# ===== SERVER CONFIGURATION =====
server.port=8080

# ===== LOGGING CONFIGURATION =====
logging.level.com.kuhub=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===== SWAGGER =====
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html