name: KUHUB Deploy

on:
  push:
    tags:
      - 'K*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kuhub-app:backend-${{ steps.vars.outputs.tag }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kuhub-app:frontend-${{ steps.vars.outputs.tag }}
          build-args: VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Deploy to AWS
        run: |
          echo "${{ secrets.KUHUB_MASTER_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_REMOTE_USER }}@${{ secrets.AWS_REMOTE_HOST }} << 'EOF'
            cd ~/kuhub-app
            sed -i "s/^TAG=.*/TAG=${{ steps.vars.outputs.tag }}/" .env
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -af
          EOF
          rm key.pem