name: Build Manual (Con Opción de Subir)

# SE ACTIVA SOLO CUANDO TÚ QUIERAS (MANUAL)
on:
  workflow_dispatch:
    inputs:
      guardar_en_dockerhub:
        description: '¿Guardar imagen en Docker Hub?'
        required: true
        default: false    # <--- POR DEFECTO NO GUARDA NADA (Solo prueba)
        type: boolean

jobs:
  build-manual:
    runs-on: ubuntu-latest

    # ======================================================
    # AQUÍ ESTÁ EL ACCESO A TUS SECRETS DE GIT
    # GitHub "abre" la caja fuerte y se la pasa a tu App
    # ======================================================
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Descargar Código (De la rama seleccionada)
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Solo nos logueamos si decidiste guardar la imagen
      - name: Login en Docker Hub
        if: ${{ inputs.guardar_en_dockerhub == true }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # CONSTRUCCIÓN
      - name: Construir (y Guardar solo si es obligatorio)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          # AQUÍ ESTÁ EL TRUCO:
          # Si la casilla está vacía (false) -> Solo construye y prueba (NO SUBE).
          # Si la casilla está marcada (true) -> Sube la imagen a Docker Hub.
          push: ${{ inputs.guardar_en_dockerhub }}

          # Usa automáticamente el nombre de la rama (ej: martorias/kuhub-backend:mi-rama)
          tags: martorias/kuhub-backend:${{ github.ref_name }}